[package]
name = "tower_defense_gui"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17", features = ["dynamic_linking"] }
tower_defense_plugin = { version = "0.1.0", path = "../tower_defense_plugin" }
wgpu-types = "26.0.0"
